name: "Dauflo Monorepo Docker Manager"
description: "This action will manager the build and push of your docker images. It will rebuild and push online if there had been a change between two releases"
inputs:
  access-token:
    description: "Access token to auth the action on the repo"
  ref:
    description: "The branch or tag ref that triggered the workflow run"

runs:
  using: "node12"
  main: "index.js"